// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh41R4tH0H0LKUB991amQg1cVhzuuA3o0',
    appId: '1:9908382410:web:bd4e8281263e018fb4e233',
    messagingSenderId: '9908382410',
    projectId: 'tyamo-app21',
    authDomain: 'tyamo-app21.firebaseapp.com',
    storageBucket: 'tyamo-app21.firebasestorage.app',
    measurementId: 'G-EQSD1VVMGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_jBhvHKzRLSUeG_HemgvfV_FNKc-Y7FU',
    appId: '1:9908382410:android:276c5e79790b42c4b4e233',
    messagingSenderId: '9908382410',
    projectId: 'tyamo-app21',
    storageBucket: 'tyamo-app21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsT_pSnV5W98dxwfBOZvhrcHjuK4JjamE',
    appId: '1:9908382410:ios:35cd10c9746a2a99b4e233',
    messagingSenderId: '9908382410',
    projectId: 'tyamo-app21',
    storageBucket: 'tyamo-app21.firebasestorage.app',
    iosBundleId: 'com.example.tyamo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsT_pSnV5W98dxwfBOZvhrcHjuK4JjamE',
    appId: '1:9908382410:ios:35cd10c9746a2a99b4e233',
    messagingSenderId: '9908382410',
    projectId: 'tyamo-app21',
    storageBucket: 'tyamo-app21.firebasestorage.app',
    iosBundleId: 'com.example.tyamo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBh41R4tH0H0LKUB991amQg1cVhzuuA3o0',
    appId: '1:9908382410:web:91811bbc97109d49b4e233',
    messagingSenderId: '9908382410',
    projectId: 'tyamo-app21',
    authDomain: 'tyamo-app21.firebaseapp.com',
    storageBucket: 'tyamo-app21.firebasestorage.app',
    measurementId: 'G-09HD4NY0GV',
  );
}
